project:
  type: website


website:
  title: "Rishabh Tewari"
  navbar:
    right:
      # - about.qmd
      - archives.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/FReeshabh
      - icon: linkedin
        href: https://www.linkedin.com/in/rishabhtewari/
      # - icon: twitter
        # href: https://twitter.com
  page-footer: "Copyright 2025, Rishabh Tewari" 
  google-analytics: "G-N73CY9VNNS"
  search: false
  favicon: favicon.ico


  sidebar:
    style: "floating"
    contents:
      - index.qmd
      # - about.qmd
      - blog.qmd
      - archives.qmd      

      # - section: "Basics"
      #   contents:
      #     - index.qmd
      #     - basics-knitr.qmd
      #     - basics-jupyter.qmd
      # - section: "Layout"
      #   contents:
      #     - layout.qmd
      #     - layout-knitr.qmd
      #     - layout-jupyter.qmd

format:
  html:
    theme: cosmo
    css: styles.css



